export interface RedactedEvidence {
  schemaVersion: '1.0';
  generatedAt: Date | string;
  integration: {
    name: string;
    mode: string;
    environment: string;
  };
  event: {
    correlationKey: string;
    bodyHash: string;
    firstSeenAt: Date | string;
    lastSeenAt: Date | string;
  };
  attempts: Array<{
    id: string;
    sequence: number;
    method: string;
    receivedAt: Date | string;
    responseStatus: number;
    responseDelayMs: number;
    signatureProvider: string;
    signatureStatus: string;
    contractResult: unknown;
  }>;
  deliveries: Array<{
    id: string;
    sequence: number;
    kind: string;
    state: string;
    statusCode: number | null;
    latencyMs: number | null;
    errorCategory: string | null;
    startedAt: Date | string;
    completedAt: Date | string | null;
  }>;
  report: {
    status: string;
    score: number | null;
    result: unknown;
  } | null;
  redacted: true;
  redactions: string[];
  expiresAt?: Date | string | null;
}

function isoDate(value: Date | string | null): string {
  if (value === null) return '—';
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toISOString();
}

function markdownCell(value: unknown): string {
  if (value === null || value === undefined || value === '') return '—';
  return String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function contractStatus(value: unknown): string {
  if (!value || typeof value !== 'object') return 'not configured';
  const contract = value as { configured?: unknown; passed?: unknown };
  if (contract.configured !== true) return 'not configured';
  return contract.passed === true ? 'passed' : 'failed';
}

export function evidenceFilename(eventId: string, format: 'json' | 'markdown'): string {
  return `hooktrials-evidence-${eventId.slice(0, 8)}.${format === 'json' ? 'json' : 'md'}`;
}

export function evidenceJson(evidence: RedactedEvidence): string {
  return `${JSON.stringify(evidence, null, 2)}\n`;
}

export function evidenceMarkdown(evidence: RedactedEvidence): string {
  const lines = [
    '# HookTrials reliability evidence',
    '',
    '> Redacted, read-only operational evidence. Payloads, captured headers, secrets, credentials and destination URLs are excluded.',
    '',
    `Generated: ${isoDate(evidence.generatedAt)}`,
    ...(evidence.expiresAt ? [`Expires: ${isoDate(evidence.expiresAt)}`] : []),
    `Schema: ${evidence.schemaVersion}`,
    '',
    '## Integration',
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Name | ${markdownCell(evidence.integration.name)} |`,
    `| Mode | ${markdownCell(evidence.integration.mode)} |`,
    `| Environment | ${markdownCell(evidence.integration.environment)} |`,
    '',
    '## Event',
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Correlation key | ${markdownCell(evidence.event.correlationKey)} |`,
    `| Body hash | ${markdownCell(evidence.event.bodyHash)} |`,
    `| First seen | ${isoDate(evidence.event.firstSeenAt)} |`,
    `| Last seen | ${isoDate(evidence.event.lastSeenAt)} |`,
    '',
    '## Inbound attempts',
    '',
    '| # | Received | Request | Response | Delay | Signature | Contract |',
    '| ---: | --- | --- | ---: | ---: | --- | --- |',
    ...evidence.attempts.map(
      (attempt) =>
        `| ${attempt.sequence} | ${isoDate(attempt.receivedAt)} | ${markdownCell(attempt.method)} | ${attempt.responseStatus} | ${attempt.responseDelayMs} ms | ${markdownCell(`${attempt.signatureProvider} · ${attempt.signatureStatus}`)} | ${contractStatus(attempt.contractResult)} |`,
    ),
    '',
    '## Destination deliveries',
    '',
    '| # | Started | Kind | State | HTTP | Latency | Error |',
    '| ---: | --- | --- | --- | ---: | ---: | --- |',
    ...evidence.deliveries.map(
      (delivery) =>
        `| ${delivery.sequence} | ${isoDate(delivery.startedAt)} | ${markdownCell(delivery.kind)} | ${markdownCell(delivery.state)} | ${markdownCell(delivery.statusCode)} | ${delivery.latencyMs === null ? '—' : `${delivery.latencyMs} ms`} | ${markdownCell(delivery.errorCategory)} |`,
    ),
    '',
    '## Resilience report',
    '',
    evidence.report
      ? `Status: ${markdownCell(evidence.report.status)} · Score: ${markdownCell(evidence.report.score)}/100`
      : 'No completed report was available when this evidence was generated.',
    '',
    '## Redactions',
    '',
    ...evidence.redactions.map((redaction) => `- ${redaction}`),
    '',
    'Generated by HookTrials.',
    '',
  ];
  return lines.join('\n');
}
