import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Brand } from '../components/Brand';
import { apiRequest, readableError } from '../lib/api';
import { timeAgo } from '../lib/format';
import type { PublicMonitorStatus } from '../lib/types';

export function StatusPage() {
  const { token = '' } = useParams();
  const [status, setStatus] = useState<PublicMonitorStatus | null>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    const load = () =>
      apiRequest<{ status: PublicMonitorStatus }>(`/v1/status/${token}`)
        .then((response) => {
          if (!cancelled) {
            setStatus(response.status);
            setError('');
          }
        })
        .catch((requestError) => {
          if (!cancelled) setError(readableError(requestError));
        });
    void load();
    const timer = window.setInterval(() => void load(), 30_000);
    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [token]);

  return (
    <main className="ht-status-page">
      <header>
        <Brand />
        <a href="https://cubepath.com/" target="_blank" rel="noreferrer">
          Hosted on CubePath
        </a>
      </header>
      {error ? (
        <section className="ht-status-missing">
          <h1>Status page unavailable</h1>
          <p>The link may have been rotated or disabled by its owner.</p>
        </section>
      ) : !status ? (
        <div className="ht-skeleton tall" aria-label="Loading public status" />
      ) : (
        <article className="ht-public-status">
          <header>
            <div>
              <p className="ht-kicker">Public integration status</p>
              <h1>{status.name}</h1>
              <span>
                {status.resourceType.replaceAll('_', ' ')} · {status.environment} ·{' '}
                {status.displayHost}
              </span>
            </div>
            <strong className={`ht-public-state ${status.state}`}>{status.state}</strong>
          </header>
          <section className="ht-status-metrics">
            <div>
              <span>Availability 24h</span>
              <b>{status.metrics.availability24h ?? '—'}%</b>
            </div>
            <div>
              <span>Average latency</span>
              <b>{status.metrics.averageLatencyMs ?? '—'} ms</b>
            </div>
            <div>
              <span>p95 latency</span>
              <b>{status.metrics.p95LatencyMs ?? '—'} ms</b>
            </div>
            <div>
              <span>Checks 24h</span>
              <b>{status.metrics.checks24h}</b>
            </div>
          </section>
          <section className="ht-status-history">
            <header>
              <h2>Latest checks</h2>
              <span>Updates every 30 seconds</span>
            </header>
            {status.checks.length === 0 ? (
              <p>No public check evidence yet.</p>
            ) : (
              <div className="ht-status-bars" aria-label="Recent check outcomes">
                {[...status.checks].reverse().map((check) => (
                  <i
                    key={check.id}
                    className={check.outcome}
                    title={`${check.outcome} · ${timeAgo(check.startedAt)}`}
                  />
                ))}
              </div>
            )}
            {status.metrics.latest ? (
              <p>
                Latest check {timeAgo(status.metrics.latest.startedAt)} ·{' '}
                {status.metrics.latest.outcome} · {status.metrics.latest.latencyMs ?? '—'} ms
              </p>
            ) : null}
          </section>
          <section className="ht-status-incidents">
            <header>
              <h2>Incident history</h2>
              <span>{status.incidents.length} retained</span>
            </header>
            {status.incidents.length === 0 ? (
              <p>No incident recorded in the shared history.</p>
            ) : (
              status.incidents.map((incident) => (
                <article key={incident.id}>
                  <span
                    className={`ht-monitor-state ${incident.status === 'open' ? 'down' : 'healthy'}`}
                  >
                    {incident.status}
                  </span>
                  <div>
                    <b>{incident.summary}</b>
                    <small>
                      {incident.cause} · opened {timeAgo(incident.openedAt)}
                    </small>
                  </div>
                </article>
              ))
            )}
          </section>
          <footer>
            <span>Evidence generated by HookTrials · refreshed {timeAgo(status.generatedAt)}</span>
            <a href="https://github.com/IKER-36/hooktrials" target="_blank" rel="noreferrer">
              Open-source reliability control plane
            </a>
          </footer>
        </article>
      )}
    </main>
  );
}
